# Generated by Django 3.1.5 on 2021-02-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='question',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='title',
        ),
    ]
