# Generated by Django 3.1.5 on 2021-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('word1', models.CharField(max_length=50)),
                ('freq1', models.PositiveIntegerField()),
                ('word2', models.CharField(max_length=50)),
                ('freq2', models.PositiveIntegerField()),
                ('word3', models.CharField(max_length=50)),
                ('freq3', models.PositiveIntegerField()),
                ('word4', models.CharField(max_length=50)),
                ('freq4', models.PositiveIntegerField()),
                ('word5', models.CharField(max_length=50)),
                ('freq5', models.PositiveIntegerField()),
                ('word6', models.CharField(max_length=50)),
                ('freq6', models.PositiveIntegerField()),
                ('word7', models.CharField(max_length=50)),
                ('freq7', models.PositiveIntegerField()),
                ('word8', models.CharField(max_length=50)),
                ('freq8', models.PositiveIntegerField()),
                ('word9', models.CharField(max_length=50)),
                ('freq9', models.PositiveIntegerField()),
                ('word10', models.CharField(max_length=50)),
                ('freq10', models.PositiveIntegerField()),
            ],
        ),
    ]
